name: Push component to ESP-IDF Component Registry

on:
  push:
    tags:
      - v*

jobs:
  upload_component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload component to registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "esp-idf-wifi-provisioner:."
          namespace: "michmich"
          version: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '' }}
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
